const CartActionTypes = {
  TOGGLE_WHISH_LIST_CART_HIDDEN: 'TOGGLE_WHISH_LIST_CART_HIDDEN',
  ADD_ITEM_WHISH_LIST: 'ADD_ITEM_WHISH_LIST',
  CLEAR_WHISH_LIST_FROM_CART: 'CLEAR_WHISH_LIST_FROM_CART',
  REMOVE_ITEM_FROM_WHISH_LIST: 'REMOVE_ITEM_FROM_WHISH_LIST'

}
export default CartActionTypes
