export const ProfileActionTypes = {
    REGISTER_FAIL: 'REGISTER_FAIL',
    PROFILE_JUST_UPDATED: 'PROFILE_JUST_UPDATED',
    PROFILE_LOADED: 'PROFILE_LOADED',
    AUTH_ERROR: 'AUTH_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    CLEAR_PROFILE: 'CLEAR_PROFILE',
    LOGOUT: 'LOGOUT'
  }
  